### ISSUE TITLE
OSError: [WinError 127]  I'm having collision issues

### ISSUE THREAD

**Issue by seungeunyu** [kakaobrain/nerf-factory#30]
Hello,

I tried to install the requirements.txt and run the model. But, I'm having problem with torch_scatter library.

Traceback (most recent call last):
  File "D:/nerf-factory/run.py", line 26, in <module>
    from utils.select_option import select_callback, select_dataset, select_model
  File "D:\nerf-factory\utils\select_option.py", line 19, in <module>
    from src.model.dvgo.model import LitDVGO
  File "D:\nerf-factory\src\model\dvgo\model.py", line 23, in <module>
    import src.model.dvgo.dcvgo as dcvgo
  File "D:\nerf-factory\src\model\dvgo\dcvgo.py", line 17, in <module>
    import torch_scatter
  File "C:\Users\clair\Anaconda3\envs\nerf_factory\lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Users\clair\Anaconda3\envs\nerf_factory\lib\site-packages\torch\_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "C:\Users\clair\Anaconda3\envs\nerf_factory\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 지정된 프로시저를 찾을 수 없습니다.

To solve this error, I've been told to downgrade torch version to under 1.5.1, but it seems the nerf-factory require torch version higher than 1.11.0.

Could you help me?

**Comment by jeongyw12382** [comment]
Could you provide more details about the environment you are working with? 
One tricky solution is to remove DVGO if you are not using it.

**Comment by jeongyw12382** [comment]
Closing the issue since no response has been given a day. Please re-open the issue whenever you confront further issues.
